let user=JSON.parse(localStorage.getItem('sh_user')||'null');let guessSecret=0,guessTries=0,memorySeq=[];const $=id=>document.getElementById(id);async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});return r.json()}
async function login(){const name=$('name').value.trim();if(!name)return alert('Введи нікнейм');const res=await api('/api/login',{method:'POST',body:JSON.stringify({name})});if(res.error)return alert(res.error);user=res;localStorage.setItem('sh_user',JSON.stringify(user));showApp()}
async function showApp(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('userBox').textContent='👤 '+user.name;updateUser(user);const q=await api('/api/daily');$('q').textContent=q.q;$('answers').innerHTML=q.a.map((x,i)=>`<button class="answer" onclick="answer(${i},this)">${x}</button>`).join('');guessSecret=Math.floor(Math.random()*20)+1;guessTries=0;loadAll()}
function updateUser(u){user=u;localStorage.setItem('sh_user',JSON.stringify(u));$('points').textContent=u.points;$('coins').textContent=u.coins||0;$('streak').textContent=u.streak;$('level').textContent=u.points>=1500?'Легенда':u.points>=800?'Майстер':u.points>=400?'Про':'Новачок'}
async function answer(i,btn){document.querySelectorAll('.answer').forEach(x=>x.disabled=true);const q=await api('/api/daily');const res=await api('/api/answer',{method:'POST',body:JSON.stringify({userId:user.id,correct:i===q.correct})});btn.classList.add(res.correct?'good':'bad');$('answerResult').textContent=res.alreadyAnswered?'Вже відповідав сьогодні.':res.correct?'🔥 Правильно! +50 XP':'❌ Неправильно. +5 XP';updateUser(res);loadAll()}
async function startGame(){if(window.playing)return;window.playing=true;$('gameStart').disabled=true;$('game').innerHTML='<div class="timer">3</div>';for(const n of [3,2,1]){await wait(500);$('game .timer').textContent=n}await wait(500);$('game').innerHTML='<button class="tap" onclick="gameClick()">НАТИСКАЙ! <b>0</b>/10</button>';window.clicks=0;window.started=performance.now()}async function gameClick(){window.clicks++;const b=document.querySelector('.tap b');if(b)b.textContent=window.clicks;if(window.clicks===10){window.playing=false;const ms=Math.round(performance.now()-window.started);const res=await api('/api/game',{method:'POST',body:JSON.stringify({userId:user.id,time:ms})});$('game').innerHTML=`<div class="win">⚡ ${ms} мс<br><small>+${res.reward} XP · +${res.coins} 🪙</small></div>`;$('gameStart').disabled=false;updateUser(res);loadAll()}}
function guess(){const n=Number($('guessInput').value);if(!n||guessTries>=5)return;guessTries++;if(n===guessSecret){finishMini('guess');$('guessResult').textContent='🎉 Вгадав! Нагорода нарахована.';guessSecret=Math.floor(Math.random()*20)+1;guessTries=0;return}$('guessResult').textContent=n<guessSecret?'⬆️ Більше!': '⬇️ Менше!';if(guessTries===5){$('guessResult').textContent='😅 Спроби закінчились. Число: '+guessSecret;guessSecret=Math.floor(Math.random()*20)+1;guessTries=0}}
async function finishMini(type){const res=await api('/api/mini',{method:'POST',body:JSON.stringify({userId:user.id,type})});updateUser(res);loadAll()}
async function memoryStart(){const len=4+Math.min(2,Math.floor((user.points||0)/500));memorySeq=Array.from({length:len},()=>Math.floor(Math.random()*4));$('memory').innerHTML=`<div class="memoryShow">${memorySeq.map(n=>['🔴','🟢','🔵','🟡'][n]).join(' ')}</div>`;$('memoryStart').disabled=true;setTimeout(()=>{ $('memory').innerHTML='<div class="memoryBtns">'+[0,1,2,3].map(n=>`<button onclick="memoryPick(${n})">${['🔴','🟢','🔵','🟡'][n]}</button>`).join('')+'</div>';window.memPos=0},1300)}async function memoryPick(n){if(n!==memorySeq[window.memPos]){ $('memory').innerHTML='❌ Не вийшло. Спробуй ще раз.';$('memoryStart').disabled=false;return}window.memPos++;if(window.memPos===memorySeq.length){$('memory').innerHTML='🎉 Памʼять пройдена!';$('memoryStart').disabled=false;await finishMini('memory')}}
async function claimBonus(){const res=await api('/api/bonus',{method:'POST',body:JSON.stringify({userId:user.id})});$('bonusResult').textContent=res.already?'🎁 Вже забрано сьогодні!':`🎉 +${res.reward} XP · +${res.coins} 🪙`;updateUser(res);$('bonusBtn').disabled=true;loadAll()}
async function loadAll(){loadBoard();loadBonusState();loadMissions();loadShop()}async function loadBonusState(){const r=await api('/api/bonus/state?userId='+user.id);$('bonusBtn').disabled=r.claimed}async function loadBoard(){const list=await api('/api/leaderboard');$('leaders').innerHTML=list.length?list.map((x,i)=>`<div class="leader"><b>${['🥇','🥈','🥉'][i]||('#'+(i+1))}</b><span>${esc(x.name)}</span><span class="score">${x.points} XP · ${x.coins} 🪙</span></div>`).join(''):'Поки що ніхто не грає.'}async function loadMissions(){const m=await api('/api/missions?userId='+user.id);$('missions').innerHTML=m.map(x=>`<div class="mission"><div><b>${x.icon} ${x.title}</b><small>${x.progress}/${x.goal}</small></div><div class="bar"><i style="width:${Math.min(100,x.progress/x.goal*100)}%"></i></div><span>${x.done?'✅':`+${x.reward} 🪙`}</span></div>`).join('')}async function loadShop(){const s=await api('/api/shop?userId='+user.id);$('shop').innerHTML=s.map(x=>`<div class="skin ${x.owned?'owned':''}"><div class="skinIcon" style="--c:${x.color}">👤</div><b>${x.name}</b><small>${x.owned?'Власний':x.price+' 🪙'}</small><button ${x.owned?'disabled':''} onclick="buy(${x.id})">${x.owned?'ВИБРАНО':'КУПИТИ'}</button></div>`).join('')}async function buy(id){const r=await api('/api/shop/buy',{method:'POST',body:JSON.stringify({userId:user.id,itemId:id})});if(r.error)return alert(r.error);updateUser(r);loadShop()}function wait(ms){return new Promise(r=>setTimeout(r,ms))}function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}if(user)showApp();
